keys:
  - &user-alex age12fax0zpagajslnlcqhtmn6s5kg2p6h6t7uuuzlsn3szw8skjgs5qegsq6z
  - &user-admin age1j6r6hexj9f5jtl0rpg5ekcr5ysvwf94mtzzx4hnpmlxvx97xfp3sek95tg
  - &host-helsinki age1ty08t00ph87qcspdf5sactd38l45s7x9eaqzx2a0atntl8trndcstrjlx9
  - &host-lenovo age1n96ardkhhewk6rq4mzmslrl80pk0dnf09vahqd3kj7nccht9m32sj00d2a
  - &host-laptop age10g0uxdzwp5f6z4dduma2eyzexve8qe8u36x2d9uuq95z44uahslsvv6y2k
  - &host-friday age1jzztt2yus45ehsy27vw9pfw42mcfr2swttduy0hqlfawej7ydczsx2ua0c
  - &host-glesys age18lyyvydaj58v0ysqe7ptq5j70zq8pfzjga5w0vvceejhagmutv5suc2ned
  - &host-phone age18uw7lxqzaqc4qm5ule2n4kzuzjxc2necau59v0x6rn4am06j857q8rgmeu
  - &host-stationary age19x6nu698a72dwv9x4rcpxgas785cxnl67jh8pgqapdqg4mzldghs7jkeqs
creation_rules:
  - path_regex: hosts/stationary/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-stationary
  - path_regex: hosts/phone/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-phone
  - path_regex: hosts/glesys/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-glesys
  - path_regex: hosts/friday/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-friday
  - path_regex: hosts/lenovo/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-lenovo
  - path_regex: hosts/helsinki/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-helsinki
  - path_regex: hosts/laptop/secrets.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-laptop
  - path_regex: users/.*-enc.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-helsinki
          - *host-lenovo
  - path_regex: domains/.*-enc.yaml
    key_groups:
      - age:
          - *user-admin
          - *host-helsinki
          - *host-lenovo
