key-file: ./keys.txt
host-key-file: /srv/storage/host/keys.txt
dns-suffix: .kompismoln.se
key-admin: keyservice
secrets:
  root: root/$entity-enc.yaml
  host: hosts/$entity/secrets.yaml
  user: users/$entity-enc.yaml
  domain: domains/$entity-enc.yaml
public-file:
  host: hosts/$entity/$type.$pubext
  user: users/$entity-$type.$pubext
  domain: domains/$entity-$type.$pubext
entities:
  root-1: &root-1 age1cavc8kaykuqxk9xk6ca78fea73ym32ugxvhq9ek0xgg0aar23qpqg5psm3
  host-stationary: &host-stationary age15pv6x0rjv5x92daey2c0yg3lk926h8zprtku32uzp0a3fqskqa0q2wq8z6
  host-lenovo: &host-lenovo age14exhy3ck8m795zsm2mcck03d65w6xhryectwgxtj8w78re8lcuasrztl6y
  user-alex: &user-alex age18hl27m8zv5lclv2r89ltv5n0mpk5sr8s23fec3ve9sj0qufh2uqq4ccstz
  host-helsinki: &host-helsinki age1pt8lptn7pz0uh09n6c7ys5455qp28c27xzg8mwp65f3wrmymmq8syqf6xa
  user-admin: &user-admin age1hu7gh8r6knwss6lkm5vf8dyfuxc536ym970mx78phv04ev74c9mq6lx44n
  user-keyservice: &user-keyservice age177cjrw3q7p2nwf44ljswflghcx9vxd05qqe9rdhe7rdrghe3ye9swznuw2
  host-iso: &host-iso age1dr88a544hn400m9euguppp92w56l59t5xtysr29lnu8wljtftqusd38sdt
  host-adele: &host-adele age19qc5cv0sutfd5r2ygpl2vwy2cf6che0zhkpz2vthjmt7qljrk47qgn46vy
  user-ami: &user-ami age1avku5tyyvu9ndlqfcvd7r4nme84alce4f3shpqrxr93e8a747amskte558
creation_rules:
  - path_regex: users/admin-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
          - *host-adele
  - path_regex: users/alex-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
  - path_regex: users/ami-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-ami
          - *host-adele
  - path_regex: domains/.*-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
  - auto: true
    path_regex: hosts/stationary/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-stationary
  - auto: true
    path_regex: hosts/lenovo/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-lenovo
  - auto: true
    path_regex: users/alex-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-alex
  - auto: true
    path_regex: hosts/helsinki/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
  - auto: true
    path_regex: users/admin-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-admin
  - auto: true
    path_regex: users/keyservice-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-keyservice
  - auto: true
    path_regex: hosts/iso/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-iso
  - auto: true
    path_regex: hosts/adele/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-adele
  - auto: true
    path_regex: users/ami-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-ami
