keys:
  - &user_admin age1j6r6hexj9f5jtl0rpg5ekcr5ysvwf94mtzzx4hnpmlxvx97xfp3sek95tg
  - &host_helsinki age1ty08t00ph87qcspdf5sactd38l45s7x9eaqzx2a0atntl8trndcstrjlx9
  - &host_lenovo age1n96ardkhhewk6rq4mzmslrl80pk0dnf09vahqd3kj7nccht9m32sj00d2a
  - &host_laptop age10g0uxdzwp5f6z4dduma2eyzexve8qe8u36x2d9uuq95z44uahslsvv6y2k
  - &host_friday age1jzztt2yus45ehsy27vw9pfw42mcfr2swttduy0hqlfawej7ydczsx2ua0c
  - &host_glesys age18lyyvydaj58v0ysqe7ptq5j70zq8pfzjga5w0vvceejhagmutv5suc2ned
  - &host_phone age18uw7lxqzaqc4qm5ule2n4kzuzjxc2necau59v0x6rn4am06j857q8rgmeu
  - &host_stationary age19x6nu698a72dwv9x4rcpxgas785cxnl67jh8pgqapdqg4mzldghs7jkeqs
creation_rules:
  - path_regex: hosts/stationary/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_stationary
  - path_regex: hosts/phone/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_phone
  - path_regex: hosts/glesys/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_glesys
  - path_regex: hosts/friday/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_friday
  - path_regex: hosts/lenovo/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_lenovo
  - path_regex: hosts/helsinki/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_helsinki
  - path_regex: hosts/laptop/secrets.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_laptop
  - path_regex: tools/secrets.template.yaml
    key_groups:
      - age:
          - *user_admin
          - *user_admin
  - path_regex: secrets/users.yaml
    key_groups:
      - age:
          - *user_admin
          - *host_helsinki
          - *host_lenovo
