keys:
  - &root-1 age1cavc8kaykuqxk9xk6ca78fea73ym32ugxvhq9ek0xgg0aar23qpqg5psm3
  - &host-stationary age15pv6x0rjv5x92daey2c0yg3lk926h8zprtku32uzp0a3fqskqa0q2wq8z6
  - &host-lenovo age14exhy3ck8m795zsm2mcck03d65w6xhryectwgxtj8w78re8lcuasrztl6y
  - &user-alex age18hl27m8zv5lclv2r89ltv5n0mpk5sr8s23fec3ve9sj0qufh2uqq4ccstz
  - &host-helsinki age1pt8lptn7pz0uh09n6c7ys5455qp28c27xzg8mwp65f3wrmymmq8syqf6xa
  - &user-admin age155m853rh0wqk4eejf955mt3j6hx0r6qjp6g3tcyp8hdg03tmyccq2vn55w
key-file: ./keys.txt
host-secrets: "['{type}'] hosts/{host}/secrets.yaml"
user-secrets: "['{user}']['{type}'] users/{user}-enc.yaml"
domain-secrets: "['{domain}']['{type}'] domains/{domain}-enc.yaml"
host-pub: hosts/{host}/{type}.pub
user-pub: users/{user}-{type}.pub
domain-pub: domains/{domain}-{type}.pem
creation_rules:
  - path_regex: hosts/helsinki/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
  - path_regex: hosts/lenovo/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-lenovo
  - path_regex: hosts/stationary/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-stationary
  - path_regex: users/.*-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
  - path_regex: domains/.*-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
