dns-suffix: .km
key-admin: keyservice
secrets:
  root: keys/root-$entity
  host: hosts/$entity/secrets.yaml
  user: users/$entity-enc.yaml
  domain: domains/$entity-enc.yaml
public-file:
  host: hosts/$entity/$type.$pubext
  user: users/$entity-$type.$pubext
  domain: domains/$entity-$type.$pubext
identities:
  root-1: &root-1 age1cavc8kaykuqxk9xk6ca78fea73ym32ugxvhq9ek0xgg0aar23qpqg5psm3
  host-adele: &host-adele age19qc5cv0sutfd5r2ygpl2vwy2cf6che0zhkpz2vthjmt7qljrk47qgn46vy
  host-helsinki: &host-helsinki age1pt8lptn7pz0uh09n6c7ys5455qp28c27xzg8mwp65f3wrmymmq8syqf6xa
  host-iso: &host-iso age1dr88a544hn400m9euguppp92w56l59t5xtysr29lnu8wljtftqusd38sdt
  host-lenovo: &host-lenovo age14exhy3ck8m795zsm2mcck03d65w6xhryectwgxtj8w78re8lcuasrztl6y
  host-stationary: &host-stationary age15pv6x0rjv5x92daey2c0yg3lk926h8zprtku32uzp0a3fqskqa0q2wq8z6
  user-admin: &user-admin age190l6kpf9l5dlmcgh6wjvn24cr7qazgrykjr653j2k6kuxma4w5mqf94qym
  user-alex: &user-alex age18hl27m8zv5lclv2r89ltv5n0mpk5sr8s23fec3ve9sj0qufh2uqq4ccstz
  user-ami: &user-ami age1avku5tyyvu9ndlqfcvd7r4nme84alce4f3shpqrxr93e8a747amskte558
  user-keyservice: &user-keyservice age177cjrw3q7p2nwf44ljswflghcx9vxd05qqe9rdhe7rdrghe3ye9swznuw2
  host-laptop: &host-laptop age17f2stt0f6yrunz0pfu3hf6rr5fcasgt7g2wyv3sq8a6a28j4jgwq2lywpy
  user-tunnelservice: &user-tunnelservice age1z44ue69etcfw69ryc7mndtepgxt65ulwndrrlqjvc5nz29fzgs0sut3agn
creation_rules:
  - path_regex: users/admin-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
          - *host-adele
          - *host-laptop
  - path_regex: users/alex-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
          - *host-laptop
  - path_regex: users/ami-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-ami
          - *host-adele
  - path_regex: domains/.*-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
          - *host-lenovo
          - *host-stationary
  - auto: true
    path_regex: hosts/adele/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-adele
  - auto: true
    path_regex: hosts/helsinki/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-helsinki
  - auto: true
    path_regex: hosts/iso/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-iso
  - auto: true
    path_regex: hosts/lenovo/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-lenovo
  - auto: true
    path_regex: hosts/stationary/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-stationary
  - auto: true
    path_regex: users/admin-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-admin
  - auto: true
    path_regex: users/alex-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-alex
  - auto: true
    path_regex: users/ami-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-ami
  - auto: true
    path_regex: users/keyservice-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-keyservice
  - auto: true
    path_regex: hosts/laptop/secrets.yaml
    key_groups:
      - age:
          - *root-1
          - *host-laptop
  - auto: true
    path_regex: users/tunnelservice-enc.yaml
    key_groups:
      - age:
          - *root-1
          - *user-tunnelservice
