name = "Kompismoln"
domain = "kompismoln.se"
contact = "info@kompismoln.se"
timezone = "Europe/Stockholm"
locale = "en_US.UTF-8"
host-config = "hosts/$host/configuration.nix"
home-config = "homes/$home.nix"
app-config = "apps/$app.nix"
build-hosts = [
  "stationary",
]
root-identities = [
  "root-1",
]
namespaces = [
  "km",
  "km1",
  "kompismoln.se",
]

[mailserver]
dkimSelector = "k1"
int = "helsinki.km"
ext = "mail.kompismoln.se"

[flake]
type = "github"
owner = "Kompismoln"
repo = "kompis-os"

[app.chatddx]
endpoint = "chatddx.com"
altpoints = ["www.chatddx.com"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.chatddx-dev]
endpoint = "chatddx-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.esse]
endpoint = "www.esse.nu"
altpoints = ["esse.nu"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.sverigesval]
endpoint = "sverigesval.org"
altpoints = ["www.sverigesval.org"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.klimatkalendern]
endpoint = "klimatkalendern.nu"
altpoints = ["www.klimatkalendern.nu"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.klimatkalendern-dev]
endpoint = "klimatkalendern-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.nextcloud-kompismoln]
endpoint = "nextcloud.kompismoln.se"
altpoints = ["nc.kompismoln.se"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.nextcloud-kompismoln-dev]
endpoint = "nextcloud-kompismoln-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.collabora]
endpoint = "collabora.kompismoln.se"
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.collabora-dev]
endpoint = "collabora-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[dns."kompismoln.se"]
mailbox = true

[dns."chatddx.com"]
mailbox = true

[dns."sverigesval.org"]
mailbox = true

[dns."ahbk.se"]
mailbox = true

[dns."esse.nu"]
mailbox = false

[dns."klimatkalendern.nu"]
mailbox = false

[public-artifacts]
default = "public-keys/$class-$entity-$key.pub"
tls-cert = "public-keys/$class-$entity-$key.pem"

[secrets]
default = "enc/$class-$entity.yaml"
root = "keys/$class-$entity"

[class.root]
keys = [
  "age-key",
]

[class.host]
keys = [
  "age-key",
  "ssh-key",
  "wg0-key",
  "wg1-key",
  "wg2-key",
  "luks-key",
]

[class.user]
keys = [
  "age-key",
  "ssh-key",
  "mail",
  "passwd",
]

[class.service]
keys = [
  "age-key",
  "ssh-key",
  "mail",
  "passwd",
  "secret-key",
  "tls-cert",
  "nix-sign",
]

[class.app]
keys = [
  "age-key",
  "secret-key",
]

[ops.rebuild]
"*" = [
  "rebuild:age-key",
]

[ops.align]
"*" = [
  "align:age-key",
]

[ops.check]
"host:luks+server" = [
  "check:luks-key",
]
"host:server" = [
  "check:age-key",
  "check:ssh-key",
]
"host-lenovo" = [
  "check:age-key",
  "check:ssh-key",
]

[ops.verify-identities]
"*" = [
  "verify:age-key",
]

[ops.verify-users]
"user-*" = [
  "verify:ssh-key",
  "verify:passwd",
  "verify:mail",
]

[ops.verify-hosts]
"host-*" = [
  "verify:wg0-key",
  "verify:wg1-key",
]

[ops.verify-services]
"service-*" = [
  "verify:ssh-key",
  "verify:tls-cert",
  "verify:passwd",
  "verify:mail",
]

[root.1]

[service.backup]
grants = [
  "host-*",
]

[service.domain-km]
grants = [
  "host-*",
]

[service.domain-km1]
grants = [
  "host-*",
]

[service."domain-kompismoln.se"]
grants = [
  "host-*",
]

[service.locksmith]
grants = [
  "host-*",
]

[service.egress-proxy]
grants = [
  "host:server",
]

[service.reverse-tunnel]
grants = [
  "host:server",
]

[service.nix-build]
grants = [
  "host-*",
]

[service.nix-push]
grants = [
  "host-*",
]

[service.nix-switch]
grants = [
  "host-*",
]

[service.nix-serve]
grants = [
  "host-*",
]

[service.rescue]
grants = [
  "host-*",
]

[service.dmarc-reports]
grants = [
  "host:mailserver",
]

[service.glesys-api]
account = "cl44748"
endpoint = "https://api.glesys.com"
grants = [
  "host-stationary",
]

[host.stationary]
facter = "hosts/stationary/facter.json"
id = 1
roles = [
  "nixos",
  "peer",
  "server",
  "comfy-root",
  "app-scheduler",
]
endpoint = "stationary.kompismoln.se"
dnsFor = "wg1"
subnets = [
  "wg0",
  "wg1",
]
system = "x86_64-linux"
stateVersion = "20.03"

[host.laptop]
id = 2
roles = [
  "nixos",
  "peer",
]
subnets = [
  "wg0",
  "wg1",
]
system = "x86_64-linux"
stateVersion = "23.11"

[host.phone]
id = 4
roles = [
  "peer",
]
subnets = [
  "wg0",
  "wg1",
]
system = "aarch64-linux"
stateVersion = ""

[host.helsinki]
facter = "hosts/helsinki/facter.json"
id = 5
roles = [
  "nixos",
  "peer",
  "webserver",
  "mailserver",
  "disko-server",
]
endpoint = "helsinki.kompismoln.se"
dnsFor = "wg0"
subnets = [
  "wg0",
  "wg1",
]
system = "x86_64-linux"
stateVersion = "25.05"

[host.friday]
id = 6
roles = [
  "nixos",
  "peer",
]
subnets = [
  "wg0",
  "wg1",
]
system = "x86_64-linux"
stateVersion = "20.03"

[host.lenovo]
id = 7
facter = "hosts/lenovo/facter.json"
roles = [
  "nixos",
  "peer",
  "comfy-root",
  "hypr-devstation",
]
subnets = [
  "wg0",
  "wg1",
]
system = "x86_64-linux"
stateVersion = "24.11"

[host.lenovo.home.alex]
roles = [
  "hypr-devstation",
]

[host.adele]
facter = "hosts/adele/facter.json"
id = 8
roles = [
  "nixos",
  "peer",
  "disko-laptop",
  "cinnamon-office",
]
subnets = [
  "wg0",
  "wg1",
]
system = "x86_64-linux"
stateVersion = "25.11"

[host.adele.home.ami]
roles = [
  "cinnamon-office",
]

[host.bootstrap]
id = 254
roles = []
system = "x86_64-linux"
stateVersion = "25.11"

[host.debian]
system = "x86_64-linux"
stateVersion = "23.11"
users = ["alex"]
roles = [
  "home-manager",
  "workstation",
]

[host.arch]
system = "x86_64-linux"
stateVersion = "24.05"
users = ["alex"]
roles = [
  "home-manager",
  "workstation",
]

[user.admin]
mail = true
grants = [
  "host-*",
]
inboxes = [
  "info@kompismoln.se",
  "postmaster@kompismoln.se",
  "abuse@kompismoln.se",
]

[user.ami]
grants = [
  "host-adele",
]

[user.alex]
mail = true
description = "Alexander Holmbäck"
email = "alex@kompismoln.se"
inboxes = [
  "alex@ahbk.se",
  "alex@klimatkalendern.nu",
]
grants = [
  "host-lenovo",
  "host-helsinki",
]

[user.johanna]
grants = [
  "host-friday",
]

[subnet.wg0]
enable = true
address = "10.0.0.0/24"
port = 51820
keepalive = 25
gateway = "helsinki"
namespace = "km"
dns = ["helsinki"]
resetOnRebuild = true
peerAddress = "10.0.0.x"
allowedTCPPortRanges = [{ from = 0, to = 65535 }]

[subnet.wg1]
enable = true
address = "10.0.1.0/24"
port = 51821
keepalive = 25
gateway = "stationary"
namespace = "km1"
dns = ["stationary"]
resetOnRebuild = true
peerAddress = "10.0.1.x"
allowedTCPPortRanges = [{ from = 0, to = 65535 }]

[theme]
wallpaper = "assets/wallpaper.jpg"

[theme.fonts]
emoji = { package = "noto-fonts-emoji", name = "Noto Color Emoji" }
monospace = { package = "source-code-pro", name = "Source Code Pro" }
serif = { package = "merriweather", name = "Merriweather" }
sansSerif = { package = "roboto", name = "Roboto" }

[theme.colors]
black-100 = "#717C7C"
black-200 = "#727169"
black-300 = "#54546D"
black-400 = "#363646"
black-500 = "#2A2A37"
black-600 = "#1F1F28"
black-700 = "#1a1a22"
black-800 = "#181820"
black-900 = "#16161D"
red-300 = "#FF5D62"
red-400 = "#C34043"
red-500 = "#E82424"
pink-300 = "#D27E99"
pink-400 = "#E46876"
pink-500 = "#43242B"
green-300 = "#98BB6C"
green-400 = "#76946A"
green-500 = "#2B3328"
yellow-300 = "#E6C384"
yellow-400 = "#DCA561"
yellow-500 = "#FF9E3B"
beige-300 = "#C0A36E"
beige-400 = "#938056"
beige-500 = "#49443C"
orange-400 = "#FFA066"
blue-200 = "#A3D4D5"
blue-300 = "#7FB4CA"
blue-400 = "#7E9CD8"
blue-500 = "#2D4F67"
blue-600 = "#223249"
blue-700 = "#252535"
purple-200 = "#b8b4d0"
purple-300 = "#9CABCA"
purple-400 = "#938AA9"
purple-500 = "#957FB8"
cyan-300 = "#7AA89F"
cyan-400 = "#6A9589"
cyan-500 = "#658594"
white-200 = "#FCF7EA"
white-300 = "#ECE7DA"
white-400 = "#DCD7BA"
white-500 = "#C8C093"

[ids]
alex = 1001
johanna = 1102
ami = 1104
esse = 3000
esse-redis = 3001
esse-dev = 3002
esse-dev-redis = 3003
klimatkalendern = 3004
klimatkalendern-dev = 3005
nextcloud-kompismoln = 3006
nextcloud-kompismoln-dev = 3007
chatddx-redis = 3008
chatddx-svelte = 3009
chatddx-django = 3010
chatddx-dev-redis = 3011
chatddx-dev-svelte = 3012
chatddx-dev-django = 3013
collabora = 3014
collabora-dev = 3015
