# org.toml
name = "Kompismoln"
endpoint = "kompismoln.se"
contact = "info@kompismoln.se"
timezone = "Europe/Stockholm"
locale = "en_US.UTF-8"
prefix = "fd17:9247:d916"
prefix4 = "10.0"
build-hosts = ["pelle", "stationary"]
root-identities = ["root-1"]
namespaces = ["km", "km1", "kompismoln.se"]

[vpn.wg0]
id = 0
trusted = true
gateway = "helsinki"
namespace = "km"
dns = ["helsinki"]

[vpn.wg1]
id = 1
trusted = true
gateway = "stationary"
proxy = true
namespace = "km1"
dns = ["stationary"]

[vpn.wg2]
id = 2
trusted = true
gateway = "pelle"
namespace = "km2"
dns = ["pelle"]

[mailserver]
dkimSelector = "k1"
host = "helsinki"
int = "helsinki.km"
ext = "mail.kompismoln.se"

[flake]
type = "github"
owner = "Kompismoln"
repo = "kompis-os"

[domain."kompismoln.se"]
mailbox = true

[domain."chatddx.com"]
mailbox = true

[domain."sverigesval.org"]
mailbox = true

[domain."ahbk.se"]
mailbox = true

[domain."esse.nu"]
mailbox = false

[domain."klimatkalendern.nu"]
mailbox = false

[public-artifacts]
default = "public-keys/$class-$entity-$key.pub"
tls-cert = "public-keys/$class-$entity-$key.pem"

[secrets]
default = "enc/$class-$entity.yaml"
root = "keys/$class-$entity"

[class.root]
keys = ["age-key"]

[class.host]
keys = [
  "age-key",
  "ssh-key",
  "wg0-key",
  "wg1-key",
  "wg2-key",
  "luks-key",
]

[class.service]
keys = [
  "age-key",
  "ssh-key",
  "mail",
  "passwd",
  "secret-key",
  "tls-cert",
  "nix-sign",
]

[class.user]
keys = [
  "age-key",
  "ssh-key",
  "mail",
  "passwd",
  "restic-key",
]

[class.app]
keys = [
  "age-key",
  "ssh-key",
  "secret-key",
  "restic-key",
]

[ops.rebuild]
"*" = ["rebuild:age-key"]

[ops.align]
"*" = ["align:age-key"]

[ops.check]
"host:luks+server" = ["check:luks-key"]
"host:server" = ["check:age-key", "check:ssh-key"]
"host-lenovo" = ["check:age-key", "check:ssh-key"]

[ops.verify-identities]
"*" = ["verify:age-key"]

[ops.verify-users]
"user-*" = ["verify:ssh-key", "verify:passwd", "verify:mail"]

[ops.verify-hosts]
"host-*" = ["verify:wg0-key", "verify:wg1-key"]

[ops.verify-services]
"service-*" = [
  "verify:ssh-key",
  "verify:tls-cert",
  "verify:passwd",
  "verify:mail",
]

[root.1]

[host.stationary]
id = 1
roles = ["nixos", "peer", "server", "app-scheduler"]
endpoint = "stationary.kompismoln.se"
vpns = [
  "wg0",
  "wg1",
  "wg2",
]
system = "x86_64-linux"
stateVersion = "25.05"
network.eth.interface = "enp3s0"

[host.stationary.disk-layouts.main]
layout = "main-server-zfs-test"
devices = "/dev/disk/by-id/ata-CT500MX500SSD1_1845E1D53DBC"

[host.stationary.disk-layouts.single-xfs]
layout = "single-xfs"
devices = "/dev/disk/by-id/ata-TOSHIBA_MK2555GSX_59EIS0BNS"
mountpoint = "/srv/xfs-1"

[host.stationary.disk-layouts.tungsten]
layout = "raid1-xfs"
devices = [
  "/dev/disk/by-id/ata-WDC_WD10EACS-00D6B0_WD-WCAU44065762",
  "/dev/disk/by-id/ata-WDC_WD10EACS-00D6B0_WD-WCAU44323396"
]
mountpoint = "/srv/tungsten"

[host.lenovo]
id = 7
roles = ["nixos", "peer", "rice"]
vpns = [
  "wg0",
  "wg1",
  "wg2",
]
system = "x86_64-linux"
stateVersion = "24.11"
# disk-layouts.main-workstation.devices = "/dev/disk/by-id/nvme-SAMSUNG_MZVLW256HEHP-000L7_S35ENX0J617479"
home.alex.roles = ["hypr-devstation", "rice"]

network.eth.interface = "enp0s31f6"
network.wifi.interface = "wlp3s0"

[host.lenovo.desktop]
audio-bus-id = "pci-0000_00_1f.3"
kb-layout = "us,se"

[[host.lenovo.monitors]]
output = "eDP-1"
mode = "preferred"
position = "auto"

[[host.lenovo.monitors]]
output = "HDMI-A-2"
mode = "1920x1080@60"
position = "auto"
scale = 1

[[host.lenovo.devices]]
name = "epic-mouse-v1"
sensitivity = -0.5

[[host.lenovo.devices]]
name = "wacom-intuos-pt-m-pen"
transform = 0
output = "HDMI-A-1"

[host.laptop]
id = 2
roles = ["nixos", "peer", "hypr-mediastation"]
vpns = [
  "wg0",
  "wg1",
  "wg2",
]
system = "x86_64-linux"
stateVersion = "26.05"
home.alex.roles = ["hypr-mediastation"]

network.eth.interface = "eth0"
network.wifi.interface = "wlp1s0"

[host.laptop.desktop]
kb-layout = "us,se"

[host.laptop.disk-layouts.main]
layout = "main-media"
devices = "/dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B77858A5120"

[host.phone]
id = 4
roles = ["peer"]
vpns = ["wg0", "wg1"]
system = "aarch64-linux"
stateVersion = ""

[host.helsinki]
id = 5
system = "x86_64-linux"
stateVersion = "25.05"
endpoint = "helsinki.kompismoln.se"
vpns = [
  "wg0",
  "wg1",
  "wg2",
]
roles = [
  "nixos",
  "peer",
  "server",
  "mailserver",
  "app-scheduler",
]

[host.helsinki.network.eth]
interface = "enp1s0"
mode = "static"
metric = 512
address4 = "65.108.214.112/32"
gateway4 = "172.31.1.1"
address = "2a01:4f9:c012:e514::1/64"
gateway = "fe80::1"
dns = [
  "185.12.64.1",
  "185.12.64.2",
  "2a01:4ff:ff00::add:1",
  "2a01:4ff:ff00::add:2",
]

[host.helsinki.disk-layouts.main]
layout = "main-server-btrfs"
devices = "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_101498674"

[host.friday]
id = 6
hardwareReport = "standard"
roles = ["nixos", "peer"]
vpns = ["wg0", "wg1"]
system = "x86_64-linux"
stateVersion = "20.03"

[host.adele]
id = 8
system = "x86_64-linux"
stateVersion = "25.11"
vpns = [
  "wg0",
  "wg1",
  "wg2",
]
roles = ["nixos", "peer", "comfy-root"]
home.ami.roles = ["cinnamon-office"]

network.wifi.interface = "wlp1s0"
network.eth.interface = "enp0s31f6"

[host.adele.disk-layouts.main]
layout = "main-workstation"
devices = "/dev/disk/by-id/ata-SanDisk_X400_M.2_2280_128GB_164787421747"

[host.pelle]
endpoint = "pelle.kompismoln.se"
id = 9
roles = [
  "nixos",
  "peer",
  "server",
  "inference-server",
  # "archive",
]
vpns = [
  "wg0",
  "wg1",
  "wg2",
]
system = "x86_64-linux"
stateVersion = "25.11"
network.eth.interface = "enp5s0"

[host.pelle.home]
alex.roles = ["cli-devstation"]

[host.pelle.disk-layouts.main]
layout = "main-server-ai"
devices = "/dev/disk/by-id/nvme-WDC_WD_BLACK_SDBPNTY-1T00-1106_21351R802985"

[host.bootstrap]
id = 254
roles = ["nixos", "peer"]
vpns = ["wg0"]
system = "x86_64-linux"
stateVersion = "25.11"

[host.debian]
id = 253
system = "x86_64-linux"
stateVersion = "23.11"
users = ["alex"]
roles = ["home-manager", "workstation"]

[host.arch]
id = 252
system = "x86_64-linux"
stateVersion = "24.05"
users = ["alex"]
roles = ["home-manager", "workstation"]

[user.admin]
id = 1000
description = "Administrator"
mail = true
email = "admin@kompismoln.se"
grants = ["host-*"]
inboxes = [
  "info@kompismoln.se",
  "postmaster@kompismoln.se",
  "abuse@kompismoln.se",
]

[user.ami]
id = 1104
description = "AMI"
grants = ["host-adele"]

[user.alex]
id = 1001
mail = true
description = "Alexander Holmbäck"
email = "alex@kompismoln.se"
inboxes = ["alex@ahbk.se", "alex@klimatkalendern.nu"]
grants = [
  "host-lenovo",
  "host-pelle",
  "host-helsinki",
  "host-laptop",
]

[user.johanna]
id = 1102
description = "Johanna"
grants = ["host-friday"]

[service.backup]
grants = ["host-*"]

[service.domain-km]
grants = ["host-*"]

[service.domain-km1]
grants = ["host-*"]

[service."domain-kompismoln.se"]
grants = ["host-*"]

[service.locksmith]
id = 2000
grants = ["host-*"]

[service.egress-proxy]
id = 2007
grants = ["host:server"]

[service.reverse-tunnel]
id = 2001
grants = ["host:server"]

[service.vllm]
id = 2009
grants = ["host:inference-server"]

[service.nix-build]
id = 2002
grants = ["host-*"]

[service.nix-push]
id = 2004
grants = ["host-*"]

[service.nix-switch]
id = 2003
grants = ["host-*"]

[service.nix-serve]
grants = ["host-*"]

[service.rescue]
grants = ["host-*"]

[service.dmarc-reports]
grants = ["host:mailserver"]

[service.glesys-api]
data.account = "cl44748"
endpoint = "https://api.glesys.com"
grants = ["host-stationary", "host-pelle"]

[app.esse]
id = 3000
endpoint = "www.esse.nu"
altpoints = ["esse.nu"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.esse-dev]
id = 3002
endpoint = "esse-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.sverigesval]
endpoint = "sverigesval.org"
altpoints = ["www.sverigesval.org"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.sverigesval-dev]
endpoint = "sverigesval-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.klimatkalendern]
id = 3004
endpoint = "klimatkalendern.nu"
altpoints = ["www.klimatkalendern.nu"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.klimatkalendern-dev]
id = 3005
endpoint = "klimatkalendern-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

# [app.klimatkalendern-dev.state]
# capture = "hourly"
# commit = "daily"
# send."host:archive" = "daily"
# keep.snapshot.daily = 24
# keep.repo = { weekly = 7, monthly = 4 }
# keep."host:archive" = { weekly = 7, monthly = 4 }

[app.opencloud-kompismoln]
id = 3020
endpoint = "opencloud.kompismoln.se"
run-on-hosts = []
grants = ["host:app-scheduler"]

[app.nextcloud-kompismoln]
id = 3006
endpoint = "nextcloud.kompismoln.se"
altpoints = ["nc.kompismoln.se"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.nextcloud-kompismoln-dev]
id = 3007
endpoint = "nextcloud-kompismoln-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.collabora]
id = 3015
endpoint = "collabora.kompismoln.se"
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.collabora-dev]
id = 3014
endpoint = "collabora-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[app.chatddx]
id = 3019
endpoint = "chatddx.com"
altpoints = ["www.chatddx.com"]
run-on-hosts = ["helsinki"]
grants = ["host:app-scheduler"]

[app.chatddx-dev]
id = 3017
endpoint = "chatddx-dev.kompismoln.se"
run-on-hosts = ["stationary"]
grants = ["host:app-scheduler"]

[store.huggingface]
id = 4000

[theme]
wallpaper = "assets/wallpaper.jpg"

[theme.fonts]
emoji = { package = "noto-fonts-color-emoji", name = "Noto Color Emoji" }
monospace = { package = "source-code-pro", name = "Source Code Pro" }
serif = { package = "merriweather", name = "Merriweather" }
sansSerif = { package = "roboto", name = "Roboto" }
