# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = lib.mkDefault {
    device = "/dev/mapper/pool-root";
    fsType = "ext4";
  };

  fileSystems."/keys" = lib.mkDefault {
    device = "/dev/mapper/pool-keys";
    fsType = "ext4";
  };

  fileSystems."/var" = lib.mkDefault {
    device = "/dev/mapper/pool-var";
    fsType = "ext4";
  };

  fileSystems."/nix" = lib.mkDefault {
    device = "/dev/mapper/pool-state";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/mnt/snapshots" = lib.mkDefault {
    device = "/dev/mapper/pool-state";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/srv/backup" = lib.mkDefault {
    device = "/dev/mapper/pool-state";
    fsType = "btrfs";
    options = [ "subvol=@backup" ];
  };

  fileSystems."/mnt/state" = lib.mkDefault {
    device = "/dev/mapper/pool-state";
    fsType = "btrfs";
  };

  fileSystems."/srv/storage" = lib.mkDefault {
    device = "/dev/mapper/pool-state";
    fsType = "btrfs";
    options = [ "subvol=@storage" ];
  };

  fileSystems."/etc/NetworkManager" = lib.mkDefault {
    device = "/srv/storage/@storage/etc/NetworkManager";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/home" = lib.mkDefault {
    device = "/srv/storage/@storage/home";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/var/lib/nixos" = lib.mkDefault {
    device = "/srv/storage/@storage/var/lib/nixos";
    fsType = "none";
    options = [ "bind" ];
  };

  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-uuid/FB00-2329";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/var/lib/systemd" = lib.mkDefault {
    device = "/srv/storage/@storage/var/lib/systemd";
    fsType = "none";
    options = [ "bind" ];
  };

  swapDevices = lib.mkDefault [
    { device = "/dev/mapper/pool-swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
